<?php

declare(strict_types=1);

namespace PhoneBurner\SaltLite\Cryptography\Hash;

use PhoneBurner\SaltLite\Cryptography\ConstantTime;
use PhoneBurner\SaltLite\Cryptography\Exception\InvalidHash;
use PhoneBurner\SaltLite\Cryptography\Symmetric\SharedKey;
use PhoneBurner\SaltLite\Filesystem\FileReader;
use PhoneBurner\SaltLite\String\Encoding\Encoding;

/**
 * Note: The default MAC algorithm is BLAKE2B, which is a secure and fast
 * cryptographic hash function, and which will produces a 256-bit digest by
 * default. This is different from the MAC generated by the
 * \PhoneBurner\SaltLite\Cryptography\Symmetric\Symmetric::sign()
 * method, which also uses BLAKE2B, but produces a 512-bit digest.
 */
final readonly class Hmac implements MessageDigest
{
    public string $digest;

    public function __construct(
        string $digest,
        public HashAlgorithm $algorithm,
        Encoding|null $encoding = null,
    ) {
        if (! $this->algorithm->cryptographic()) {
            throw new InvalidHash('Invalid Algorithm for HMAC: ' . $algorithm->name);
        }

        try {
            $this->digest = $encoding ? ConstantTime::decode($encoding, $digest) : $digest;
        } catch (\Exception $e) {
            throw new InvalidHash('Invalid Encoding for ' . $algorithm->name, previous: $e);
        }

        if (\strlen($this->digest) !== $algorithm->bytes()) {
            throw new InvalidHash('Invalid Length or Character Set for ' . $algorithm->name);
        }
    }

    /**
     * Create a new HMAC instance from a digest string with the given algorithm and encoding.
     */
    public static function make(
        string|\Stringable $digest,
        HashAlgorithm $algorithm = HashAlgorithm::BLAKE2B,
        Encoding $encoding = Encoding::Hex,
    ): self {
        return new self((string)$digest, $algorithm, $encoding);
    }

    public static function string(
        string|\Stringable $content,
        SharedKey $key,
        HashAlgorithm $algorithm = HashAlgorithm::BLAKE2B,
    ): self {
        return new self(match ($algorithm) {
            HashAlgorithm::BLAKE2B => \sodium_crypto_generichash((string)$content, $key->bytes()),
            default => \hash_hmac($algorithm->value, (string)$content, $key->bytes(), true),
        }, $algorithm);
    }

    public static function file(
        string|\Stringable $file,
        SharedKey $key,
        HashAlgorithm $algorithm = HashAlgorithm::BLAKE2B,
    ): self {
        return match ($algorithm) {
            HashAlgorithm::BLAKE2B => self::iterable(FileReader::make($file), $key, $algorithm),
            default => new self((string)\hash_hmac_file($algorithm->value, (string)$file, $key->bytes(), true), $algorithm),
        };
    }

    /**
     * @param iterable<iterable<string|\Stringable>|string|\Stringable> $pump
     */
    public static function iterable(
        iterable $pump,
        SharedKey $key,
        HashAlgorithm $algorithm = HashAlgorithm::BLAKE2B,
    ): self {
        return match ($algorithm) {
            HashAlgorithm::BLAKE2B => self::sodiumPump($key, $pump),
            default => self::hashPump($algorithm, $key, $pump),
        };
    }

    #[\Override]
    public function algorithm(): HashAlgorithm
    {
        return $this->algorithm;
    }

    #[\Override]
    public function digest(Encoding $encoding = Encoding::Hex): string
    {
        return ConstantTime::encode($encoding, $this->digest);
    }

    public function is(mixed $hash): bool
    {
        return $hash instanceof self
            && $this->algorithm === $hash->algorithm
            && \hash_equals($this->digest, $hash->digest);
    }

    #[\Override]
    public function __toString(): string
    {
        return $this->digest(Encoding::Hex);
    }

    /**
     * @param iterable<iterable<string|\Stringable>|string|\Stringable> $pump
     */
    private static function sodiumPump(SharedKey $key, iterable $pump): self
    {
        $context = \sodium_crypto_generichash_init($key->bytes());
        self::sodiumPumpUpdate($context, $pump);

        return new self(\sodium_crypto_generichash_final($context), HashAlgorithm::BLAKE2B);
    }

    /**
     * @param non-empty-string $context
     * @param iterable<iterable<string|\Stringable>|string|\Stringable> $pump
     * @phpstan-param-out non-empty-string $context
     */
    private static function sodiumPumpUpdate(string &$context, iterable $pump): void
    {
        foreach ($pump as $bucket) {
            if (\is_iterable($bucket)) {
                self::sodiumPumpUpdate($context, $bucket);
            } else {
                \assert($context !== '');
                \sodium_crypto_generichash_update($context, (string)$bucket);
            }
        }
    }

    /**
     * @param iterable<iterable<string|\Stringable>|string|\Stringable> $pump
     */
    private static function hashPump(HashAlgorithm $algorithm, SharedKey $key, iterable $pump): self
    {
        $context = \hash_init($algorithm->value, \HASH_HMAC, $key->bytes());
        self::hashPumpUpdate($context, $pump);

        return new self(\hash_final($context, true), $algorithm);
    }

    /**
     * @param iterable<iterable<string|\Stringable>|string|\Stringable> $pump
     */
    private static function hashPumpUpdate(\HashContext $context, iterable $pump): void
    {
        foreach ($pump as $bucket) {
            if (\is_iterable($bucket)) {
                self::hashPumpUpdate($context, $bucket);
            } else {
                \hash_update($context, (string)$bucket);
            }
        }
    }
}
